name: Leak Check (Valgrind - CMake)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.cpp'
      - '**.h'
      - 'CMakeLists.txt'
      - '.github/workflows/**.yml'

jobs:
  leakcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y valgrind build-essential cmake

      - name: Configure and Build with CMake
        run: |
          cmake -B build
          cmake --build build

      - name: Run memcheck with Valgrind
        run: cmake --build build --target memcheck
