name: Lint (cpplint)

on: [push, pull_request]

jobs:
  cpplint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install cpplint
        run: pip install cpplint

      - name: Run cpplint
        run: |
          CONFIG=$(cat CPPLINT.cfg)
          find . -name "*.cpp" -o -name "*.h" | xargs cpplint --$CONFIG
