name: Lint (clang-tidy)

on: [pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install clang-tidy, parallel in catch
        uses: awalsh128/cache-apt-pkgs-action@v1
        whith:
          packages: clang-tidy parallel
          version: 1.0

      - name: make build dirctory
        run: cmake -B build
      - name: clang-tidy whith parrallel
        # run: git ls-files '*.cpp' '*.hpp' | parrallel clang-tidy -p build -quiet
        run: git ls-files 'src/main.cpp' | parrallel clang-tidy -p build -quiet
