name: Unit Test (GoogleTest)

on:
  pull_request:
    paths:
      - '**.cpp'
      - '**.h'
      - '**/CMakeLists.txt'
  workflow_dispatch:

jobs:
  unittest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Install dependencies (GoogleTest)
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential

      - name: Configure and build
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Run unit tests
        run: |
          cd build
          ctest --output-on-failure
